name: Develop Build

on:
   push:
     branches:
      - develop
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build image
        if: success()
        run: docker build . -t olivenbarcelon/um-java-ws:develop
        
      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push olivenbarcelon/um-java-ws:develop
          