# Getting Started With Codecov and Java - https://about.codecov.io/language/java/
name: Java CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: |
          cd project
          mvn --batch-mode --update-snapshots verify -DskipTests
      
      - name: Build Coverage
        run: |
          cd project
          mvn cobertura:cobertura -DskipTests
      
      - name: Upload reports to codecov
        run: |
          export CODECOV_TOKEN="${{secrets.CODECOV_TOKEN}}"
          bash <(curl -s https://codecov.io/bash)