# Getting Started With Codecov and Java - https://about.codecov.io/language/java/
# Building and testing Java with Maven - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# MySQL GitHub Action - https://github.com/mirromutth/mysql-action#the-default-mysql
# How to make MySQL work in your GitHub Actions - https://ovirium.com/blog/how-to-make-mysql-work-in-your-github-actions/
# JaCoCo Code Coverage Tutorial with Spring Boot - https://www.youtube.com/watch?v=UZWOb9ce6go
# Spring 5 Reactive Project - https://github.com/eugenp/tutorials/tree/master/spring-5-reactive-2
# JaCoCo-Demo - https://github.com/dailycodebuffer/Spring-MVC-Tutorials/tree/master/JaCoCo-Demo
name: Master Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_DATABASE: ${{secrets.DB_DATABASE}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE `${{env.DB_DATABASE}}`;' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
          mysql -e 'SHOW DATABASES;' -u${{env.DB_USER}} -p${{env.DB_PASSWORD}}
      
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      
      - name: Build with Maven
        run: |
          cd project
          mvn --batch-mode --update-snapshots verify -Dresources.path=classpath
      
      - name: Upload Reports
        run: |
          bash <(curl -s https://codecov.io/bash)
          